name: CI/CD Pipeline

on:
  push:
    branches:
      - test-branch
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t hello-world-microservice .

      - name: Push Docker Image
        run: docker tag hello-world-microservice ramyavandu/hello-world-microservice:latest &&
             docker push ramyavandu/hello-world-microservice:latest

      - name: Test Docker Image Locally
        run: docker run -d -p 8090:5000 ramyavandu/hello-world-microservice:latest &&
             curl -f http://localhost:8090
